image: gradle:8.7.0-jdk17

clone:
  depth: full

definitions:
  steps:
    - step: &build
        name: Build
        caches:
          - gradle
        script:
          - chmod +x gradlew
          - ./gradlew clean build
        artifacts:
          - build/libs/**
    - step: &docker
        name: Docker Step
        caches:
          - docker
        services:
          - docker
        script:
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          - docker build -t ogabek07/ci_cd .
          - docker push ogabek07/ci_cd
    - step: &deployment
        name: Deploy to K8s
        script:
          - echo $GCLOUD_SERVICE_KEY_FILE | base64 --decode --ignore-garbage > ./gcloud-service-key.json
          - gcloud auth activate-service-account --key-file=gcloud-service-key.json
          - gcloud container clusters get-credentials cicd --zone us-central1 --project sunny-emissary-421003
          - docker build -t gcr.io/sunny-emissary-421003/ogabek07/ci_cd:latest .
          - docker push gcr.io/sunny-emissary-421003/ogabek07/ci_cd:latest
          - kubectl apply -f path/to/kubernetes-manifests
pipelines:
  pull-requests:
    '**':
      - step: *build
  branches:
    master:
      - step: *build
      - step: *docker
      - step: *deployment
