image: gradle:8.7.0-jdk17

clone:
  depth: full

definitions:
  steps:
    - step: &build
        name: Build
        caches:
          - gradle
        script:
          - chmod +x gradlew
          - ./gradlew clean build
        artifacts:
          - build/libs/**
    - step: &docker
        name: Docker Step
        caches:
          - docker
        services:
          - docker
        script:
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          - docker build -t ogabek07/ci_cd .
          - docker push ogabek07/ci_cd
    - step: &deployment
        name: Deploy to K8s
        script:
          - pipe: atlassian/google-kubernetes-engine-deploy:1.1.0
            variables:
              PROJECT_KEY: $PROJECT_KEY
              CLUSTER_NAME: "cicd"
              IMAGE: "gcr.io/sunny-emissary-421003/ogabek07/ci_cd:$BITBUCKET_COMMIT"
pipelines:
  pull-requests:
    '**':
      - step: *build
  branches:
    master:
      - step: *build
      - step: *docker
      - step: *deployment
