image: gradle:7.5.1-jdk17

clone:
  depth: full

definitions:
  steps:
    - step: &build
        name: Build
        caches:
          - gradle
        script:
          - chmod +x gradlew
          - ./gradlew clean build
        artifacts:
          - build/libs/**
    - step: &docker
        name: Docker Step
        caches:
          - docker
        services:
          - docker
        script:
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          - docker build -t ogabek07/ci_cd .
          - docker push ogabek07/ci_cd
    - step: &deployment
        name: Deploy to K8s
        deployment: master
        script:
          - pipe: atlassian/kubernetes-deploy:1.3.0
            variables:
              KUBE_CONFIG_DATA: $KUBE_CONFIG_DATA
              IMAGE: ogabek07/ci_cd
              NAMESPACE: your-namespace
              DEPLOYMENT: master
pipelines:
  pull-requests:
    '**':
      - step: *build
  branches:
    master:
      - step: *build
      - step: *docker
      - step: *deployment
