apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-demo-cluster
  template:
    metadata:
      labels:
        app: my-demo-cluster
    spec:
      containers:
        - name: my-demo-cluster
          image: "ogabek07/app:${{github.sha}}"
          ports:
            - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1