spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/cabinet
    username: postgres
    password: slark343
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    liquibase-schema: public
    default-schema: public
    enabled: false
  mail:
    host: smtp.gmail.com
    port: 465
    username: khamdamov343@gmail.com
    password: pdrmhyinruuoovht  # 2-step verification password
    protocol: smtps
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

jwt:
  access: 5 #in minutes
  secret: FF51D1E77275FBA9AF35524B9E81BC74SD05AA2E