spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/ci_cd
    username: postgres
    password: slark
  mail:
    host: smtp.gmail.com
    port: 465
    username: khamdamov343@gmail.com
    password: pdrmhyinruuoovht
    protocol: smtps
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  access: 5 #in minutes
  secret: FF51D1E77275FBA9AF35524B9E81BC74SD05AA2E