name: CI-CD

env:
  image-name: ci-cd-practice

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build
        run: gradle clean build
      - name: Login to DockerHub
        run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t ogabek07/ci-cd-practice .
      - name: Publish image to docker hub
        run: docker push ogabek07/ci-cd-practice:latest
      - name: Trigger ./run.sh on EC2
        uses: appleboy/ssh-action@master
        with:
          host: 34.201.217.173
          username: ec2-user
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: ./run.sh
  deploy:
    needs: build
    runs-on: [ci-cd]
    steps:
      - name: Run ./run.sh on EC2
        run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@34.201.217.173 './run.sh'
      - name: Login to DockerHub
        run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}}
      - name: Pull image from docker hub
        run: docker pull ogabek07/ci-cd-practice:latest
      - name: Delete old container
        run: docker rm -f ci-cd-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name ci-cd-container ogabek07/ci-cd-practice
