name: Deploy to GKE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK and Gradle
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          gradle-version: '7.x.x'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          install_component: 'gke-gcloud-auth-plugin'
          export_default_credentials: true

      - name: Build Docker image
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud auth configure-docker ogabek07
          gradle clean build
          docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}}
          docker build -t ogabek07/app:latest .
          docker push ogabek07/app:latest

      - name: Deploy to GKE
        env:
          GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          gcloud container clusters get-credentials autopilot-cluster-1 --region us-central1
          cd path/to/directory/containing/config.yaml
          kubectl apply -f config.yaml