name: Deploy to GKE

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Decode service account key and activate
        run: |
          echo $${{ secrets.SERVICE_ACCOUNT_KEY }} | base64 -d > service_account.json
          gcloud auth activate-service-account \
            --key-file=service_account.json \
            khamdamov343@gmail.com

      - name: Build Docker image
        run: gradle clean build | docker build -t gcr.io/${{secrets.GKE_PROJECT}}/ci-cd-practice:latest

      - name: Login to Container Registry
        run: gcloud auth configure-docker gcr.io/${{secrets.GKE_PROJECT}}

      - name: Push Docker image
        run: docker push gcr.io/${{secrets.GKE_PROJECT}}/ci-cd-practice:latest

      - name: Deploy to GKE
        run: kubectl apply -f deployment.yaml
