name: Deploy to GKE

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Google Cloud
        run: echo ${{ GKE_SA_KEY }} | base64 -d | gcloud auth activate-service-account --key-file=-

      - name: Build Docker image
        run: gradle clean build | docker build -t gcr.io/${{GKE_PROJECT}}/ci-cd-practice:latest

      - name: Login to Container Registry
        run: gcloud auth configure-docker gcr.io/${{GKE_PROJECT}}

      - name: Push Docker image
        run: docker push gcr.io/$GKE_PROJECT/ci-cd-practice:latest

      - name: Deploy to GKE
        run: kubectl apply -f deployment.yaml
