name: Deploy to GKE

on:
  push:
    branches:
      - master
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: us-central1
  DEPLOYMENT_NAME: github-actions-gke
  IMAGE: github-actions-gke-image
  TAG: 1.0.0
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK and Gradle
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          gradle-version: '7.x.x'

      - name: Build
        run: gradle clean build

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: |- 
          gcloud --quiet auth configure-docker

      - name: Get GKE credentials
        run: |-
          gcloud container clusters get-credentials "$CLUSTER_NAME" --zone "$GKE_ZONE"

      - name: Docker image
        run: |
          docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}}
          docker build -t ${{secrets.DOCKER_USERNAME}}/app:latest .
          docker push ${{secrets.DOCKER_USERNAME}}/app:latest

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Deploy to GKE
        run: |-
          ./kustomize edit set image ${{ DOCKER_USERNAME }}/PROJECT_ID/github-actions-gke-image:latest=${{ DOCKER_USERNAME }}/$PROJECT_ID/github-actions-gke-image:latest
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide